### ISSUE TITLE
Problem in trouble operating the generator

### ISSUE THREAD

**Issue by marciovsena** [katywings/generator-slim#10]
Msg: "Warning: Cannot use 'in' operator to search for 'data' in null Use --force to continue."

**Comment by tylersloan** [comment]
this helped me fire up my first test with this generator.
Thanks @marciovsena +1

**Comment by katywings** [comment]
Thx for your report, i will try to debug it ^^

**Comment by katywings** [comment]
@marciovsena Does your commit fix this issue?

**Comment by omarciovsena** [comment]
Yes :+1:

**Comment by katywings** [comment]
Thx a lot for you work @marciovsena!
